name: my-first-workflow
# to get trigger on every push 
on: push
jobs:
    job1:
        name : JOB1
        runs-on: ubuntu-latest
        steps:
          - name: step 1
            run: |
               pwd
               ls -ltr
               hostname
          - name: step 2 - checkout   
            uses: actions/checkout@v6.0.1
          - name: step 3
            run: echo "pwd" >> singlefile.txt
          - name: step 4
            uses: actions/upload-artifact@v4
            with: 
                 name: singlefile
                 path: ./singlefile.txt
               
     
    
           
