name: my-first-workflow
# to get trigger on every push 
on: push 
jobs:
    job1:
        name : JOB1
        runs-on: ubuntu-latest
        steps:
          - name: running single command in job1
            run: echo "this is my first github workflow"
          - name: check os release for github runner 
            run: cat /etc/os-release
    job2:
          name: JOB2
          runs-on: ubuntu-latest
          steps: 
           - name: check the hostname for runner
             run: hostname
           - name: running multiple command 
             run: |
               echo "hi from pune"
               echo "current time is 'date' "
    job3:
          name: JOB3
          needs: job1
          runs-on: ubuntu-latest
          steps: 
           - name: job with single dependency
             run: sleep 10
    job4:
          name: JOB4
          needs: [job1 , job2 , job3]
          runs-on: ubuntu-latest
          steps:
             - name: job for multiple dependencies
               run: sleep 10
               
           
